events {
    worker_connections 1024;
}

http {
    upstream auth_backend {
        server service-auth:8000;
    }

    upstream crm_backend {
        server service-crm:8000;
    }

    server {
        listen 80;
        server_name localhost;

        # Базовые настройки безопасности и производительности
        client_max_body_size 20M;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;

        server_tokens off;

        # Gzip сжатие
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;

        # Общие заголовки
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # AUTH: /api/v1/auth/login → auth:8000/login
        location /api/v1/auth/ {
            proxy_pass http://auth_backend/;
        }

        # CRM: /api/v1/crm/orders → crm:8000/orders
        location /api/v1/crm/ {
            proxy_pass http://crm_backend/;
        }

        location / {
            default_type text/html;
            charset utf-8;
            return 200 "<h1>Тут будет фронтенд.</h1><p>Страница в разработке!</p>";
        }

        # Health check самого gateway
        location /health {
            access_log off;
            return 200 "ok";
            add_header Content-Type text/plain;
        }
    }
}
