"""add roles and permissions

Revision ID: 6adb23601b73
Revises: 6c375c0c0c84
Create Date: 2026-09-08 13:58:17.941338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6adb23601b73"
down_revision: Union[str, Sequence[str], None] = "6c375c0c0c84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Определяем таблицы как sa.Table для bulk_insert
permissions_table = sa.table(
    "permissions",
    sa.column("id", sa.Integer),
    sa.column("code", sa.String),
    sa.column("description", sa.String),
)

roles_table = sa.table(
    "roles",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
)

role_permissions_table = sa.table(
    "role_permissions",
    sa.column("role_id", sa.Integer),
    sa.column("permission_id", sa.Integer),
)

user_roles_table = sa.table(
    "user_roles",
    sa.column("user_id", sa.Integer),
    sa.column("role_id", sa.Integer),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###

    # === SEED DATA ===

    # Сбрасываем sequence для предсказуемых ID
    op.execute("ALTER SEQUENCE permissions_id_seq RESTART WITH 1")
    op.execute("ALTER SEQUENCE roles_id_seq RESTART WITH 1")

    # Пермишены для API управления правами
    op.execute("""
        INSERT INTO permissions (id, code, description) VALUES
            (1, 'list_permissions', 'Просмотр списка пермишенов'),
            (2, 'create_permission', 'Создание пермишена'),
            (3, 'update_permission', 'Редактирование пермишена'),
            (4, 'delete_permission', 'Удаление пермишена'),
            (5, 'list_roles', 'Просмотр списка ролей'),
            (6, 'create_role', 'Создание роли'),
            (7, 'update_role', 'Редактирование роли'),
            (8, 'delete_role', 'Удаление роли'),
            (9, 'assign_user_roles', 'Назначение ролей пользователям')
        ON CONFLICT (code) DO NOTHING
    """)

    # Роли
    op.execute("""
        INSERT INTO roles (id, name) VALUES
            (1, 'admin'),
            (2, 'user'),
            (3, 'moderator')
        ON CONFLICT (name) DO NOTHING
    """)

    # Назначаем ВСЕ пермишены админу через CROSS JOIN
    # user и moderator не получают прав на управление — только базовый доступ
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id
        FROM roles r
        CROSS JOIN permissions p
        WHERE r.name = 'admin'
        ON CONFLICT DO NOTHING
    """)

    # Назначение ролей пользователям (безопасно через EXISTS)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name = 'users' AND table_schema = 'public'
            ) THEN
                INSERT INTO user_roles (user_id, role_id)
                SELECT u.id, r.id
                FROM (VALUES (1, 'admin'), (2, 'user')) AS mapping(uid, rname)
                INNER JOIN users u ON u.id = mapping.uid
                INNER JOIN roles r ON r.name = mapping.rname
                ON CONFLICT DO NOTHING;
            END IF;
        END $$;
    """)

    # Синхронизируем sequence после вставки
    op.execute(
        "SELECT setval('permissions_id_seq', COALESCE((SELECT MAX(id) FROM permissions), 0) + 1, false)"
    )
    op.execute(
        "SELECT setval('roles_id_seq', COALESCE((SELECT MAX(id) FROM roles), 0) + 1, false)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Очищаем seed-данные в обратном порядке
    op.execute("DELETE FROM user_roles WHERE user_id IN (1, 2)")
    op.execute("DELETE FROM role_permissions WHERE role_id IN (1, 2, 3)")
    op.execute("DELETE FROM roles WHERE id IN (1, 2, 3)")
    op.execute("DELETE FROM permissions WHERE id BETWEEN 1 AND 9")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
