"""add outbox_events table for transactional outbox pattern

Revision ID: 27dd164a2484
Revises: 9c85150192c0
Create Date: 2026-09-18 22:57:51.629970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27dd164a2484"
down_revision: Union[str, Sequence[str], None] = "9c85150192c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outboxevent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "aggregate_type",
            sa.String(length=100),
            nullable=False,
            comment="Тип агрегата, например 'customer'",
        ),
        sa.Column(
            "aggregate_id",
            sa.BigInteger(),
            nullable=False,
            comment="ID бизнес-сущности",
        ),
        sa.Column(
            "event_type",
            sa.String(length=100),
            nullable=False,
            comment="Тип события, например 'customer.created.v1'",
        ),
        sa.Column(
            "payload",
            sa.JSON(),
            nullable=False,
            comment="Сериализованное тело события (без PII)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи в outbox",
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время успешной публикации в Kafka; NULL = не обработано",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outboxevent")
    # ### end Alembic commands ###
